using System;
using System.Collections.Generic;

namespace ArthausWebStore.Models
{
    public partial class ReturnReceiptHeader
    {
        public byte[] Timestamp { get; set; }
        public string No { get; set; }
        public string SellToCustomerNo { get; set; }
        public string BillToCustomerNo { get; set; }
        public string BillToName { get; set; }
        public string BillToName2 { get; set; }
        public string BillToAddress { get; set; }
        public string BillToAddress2 { get; set; }
        public string BillToCity { get; set; }
        public string BillToContact { get; set; }
        public string YourReference { get; set; }
        public string ShipToCode { get; set; }
        public string ShipToName { get; set; }
        public string ShipToName2 { get; set; }
        public string ShipToAddress { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToContact { get; set; }
        public DateTime OrderDate { get; set; }
        public DateTime PostingDate { get; set; }
        public DateTime ShipmentDate { get; set; }
        public string PostingDescription { get; set; }
        public string PaymentTermsCode { get; set; }
        public DateTime DueDate { get; set; }
        public decimal PaymentDiscount { get; set; }
        public DateTime PmtDiscountDate { get; set; }
        public string ShipmentMethodCode { get; set; }
        public string LocationCode { get; set; }
        public string ShortcutDimension1Code { get; set; }
        public string ShortcutDimension2Code { get; set; }
        public string CustomerPostingGroup { get; set; }
        public string CurrencyCode { get; set; }
        public decimal CurrencyFactor { get; set; }
        public string CustomerPriceGroup { get; set; }
        public byte PricesIncludingVat { get; set; }
        public string InvoiceDiscCode { get; set; }
        public string CustomerDiscGroup { get; set; }
        public string LanguageCode { get; set; }
        public string SalespersonCode { get; set; }
        public int NoPrinted { get; set; }
        public string OnHold { get; set; }
        public int AppliesToDocType { get; set; }
        public string AppliesToDocNo { get; set; }
        public string BalAccountNo { get; set; }
        public string VatRegistrationNo { get; set; }
        public string ReasonCode { get; set; }
        public string GenBusPostingGroup { get; set; }
        public byte Eu3PartyTrade { get; set; }
        public string TransactionType { get; set; }
        public string TransportMethod { get; set; }
        public string VatCountryRegionCode { get; set; }
        public string SellToCustomerName { get; set; }
        public string SellToCustomerName2 { get; set; }
        public string SellToAddress { get; set; }
        public string SellToAddress2 { get; set; }
        public string SellToCity { get; set; }
        public string SellToContact { get; set; }
        public string BillToPostCode { get; set; }
        public string BillToCounty { get; set; }
        public string BillToCountryRegionCode { get; set; }
        public string SellToPostCode { get; set; }
        public string SellToCounty { get; set; }
        public string SellToCountryRegionCode { get; set; }
        public string ShipToPostCode { get; set; }
        public string ShipToCounty { get; set; }
        public string ShipToCountryRegionCode { get; set; }
        public int BalAccountType { get; set; }
        public string ExitPoint { get; set; }
        public byte Correction { get; set; }
        public DateTime DocumentDate { get; set; }
        public string ExternalDocumentNo { get; set; }
        public string Area { get; set; }
        public string TransactionSpecification { get; set; }
        public string PaymentMethodCode { get; set; }
        public string ShippingAgentCode { get; set; }
        public string PackageTrackingNo { get; set; }
        public string NoSeries { get; set; }
        public string UserId { get; set; }
        public string SourceCode { get; set; }
        public string TaxAreaCode { get; set; }
        public byte TaxLiable { get; set; }
        public string VatBusPostingGroup { get; set; }
        public decimal VatBaseDiscount { get; set; }
        public int DimensionSetId { get; set; }
        public string CampaignNo { get; set; }
        public string SellToContactNo { get; set; }
        public string BillToContactNo { get; set; }
        public string OpportunityNo { get; set; }
        public string ResponsibilityCenter { get; set; }
        public DateTime RequestedDeliveryDate { get; set; }
        public DateTime PromisedDeliveryDate { get; set; }
        public string ShippingTime { get; set; }
        public string WarehouseHandlingTime { get; set; }
        public byte LateOrderShipping { get; set; }
        public string ReturnOrderNo { get; set; }
        public string ReturnOrderNoSeries { get; set; }
        public byte AllowLineDisc { get; set; }
        public string StoreNo { get; set; }
        public int RetailStatus { get; set; }
        public string RecivingPickingNo { get; set; }
        public string MemberCardNo { get; set; }
    }
}
