using System;
using System.Collections.Generic;

namespace ArthausWebStore.Models
{
    public partial class ServiceLine
    {
        public byte[] Timestamp { get; set; }
        public int DocumentType { get; set; }
        public string DocumentNo { get; set; }
        public int LineNo { get; set; }
        public string CustomerNo { get; set; }
        public int Type { get; set; }
        public string No { get; set; }
        public string LocationCode { get; set; }
        public string PostingGroup { get; set; }
        public string Description { get; set; }
        public string Description2 { get; set; }
        public string UnitOfMeasure { get; set; }
        public decimal Quantity { get; set; }
        public decimal OutstandingQuantity { get; set; }
        public decimal QtyToInvoice { get; set; }
        public decimal QtyToShip { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal UnitCostLcy { get; set; }
        public decimal Vat { get; set; }
        public decimal LineDiscount { get; set; }
        public decimal LineDiscountAmount { get; set; }
        public decimal Amount { get; set; }
        public decimal AmountIncludingVat { get; set; }
        public byte AllowInvoiceDisc { get; set; }
        public decimal GrossWeight { get; set; }
        public decimal NetWeight { get; set; }
        public decimal UnitsPerParcel { get; set; }
        public decimal UnitVolume { get; set; }
        public int ApplToItemEntry { get; set; }
        public string ShortcutDimension1Code { get; set; }
        public string ShortcutDimension2Code { get; set; }
        public string CustomerPriceGroup { get; set; }
        public string JobNo { get; set; }
        public string JobTaskNo { get; set; }
        public int JobLineType { get; set; }
        public string WorkTypeCode { get; set; }
        public decimal OutstandingAmount { get; set; }
        public decimal QtyShippedNotInvoiced { get; set; }
        public decimal ShippedNotInvoiced { get; set; }
        public decimal QuantityShipped { get; set; }
        public decimal QuantityInvoiced { get; set; }
        public string ShipmentNo { get; set; }
        public int ShipmentLineNo { get; set; }
        public string BillToCustomerNo { get; set; }
        public decimal InvDiscountAmount { get; set; }
        public string GenBusPostingGroup { get; set; }
        public string GenProdPostingGroup { get; set; }
        public int VatCalculationType { get; set; }
        public string TransactionType { get; set; }
        public string TransportMethod { get; set; }
        public int AttachedToLineNo { get; set; }
        public string ExitPoint { get; set; }
        public string Area { get; set; }
        public string TransactionSpecification { get; set; }
        public string TaxAreaCode { get; set; }
        public byte TaxLiable { get; set; }
        public string TaxGroupCode { get; set; }
        public string VatClauseCode { get; set; }
        public string VatBusPostingGroup { get; set; }
        public string VatProdPostingGroup { get; set; }
        public string CurrencyCode { get; set; }
        public decimal OutstandingAmountLcy { get; set; }
        public decimal ShippedNotInvoicedLcy { get; set; }
        public int Reserve { get; set; }
        public decimal VatBaseAmount { get; set; }
        public decimal UnitCost { get; set; }
        public byte SystemCreatedEntry { get; set; }
        public decimal LineAmount { get; set; }
        public decimal VatDifference { get; set; }
        public decimal InvDiscAmountToInvoice { get; set; }
        public string VatIdentifier { get; set; }
        public int DimensionSetId { get; set; }
        public string TimeSheetNo { get; set; }
        public int TimeSheetLineNo { get; set; }
        public DateTime TimeSheetDate { get; set; }
        public int JobPlanningLineNo { get; set; }
        public decimal JobRemainingQty { get; set; }
        public decimal JobRemainingQtyBase { get; set; }
        public decimal JobRemainingTotalCost { get; set; }
        public decimal JobRemainingTotalCostLcy { get; set; }
        public decimal JobRemainingLineAmount { get; set; }
        public string VariantCode { get; set; }
        public string BinCode { get; set; }
        public decimal QtyPerUnitOfMeasure { get; set; }
        public byte Planned { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public decimal QuantityBase { get; set; }
        public decimal OutstandingQtyBase { get; set; }
        public decimal QtyToInvoiceBase { get; set; }
        public decimal QtyToShipBase { get; set; }
        public decimal QtyShippedNotInvdBase { get; set; }
        public decimal QtyShippedBase { get; set; }
        public decimal QtyInvoicedBase { get; set; }
        public string ResponsibilityCenter { get; set; }
        public string ItemCategoryCode { get; set; }
        public byte Nonstock { get; set; }
        public string ProductGroupCode { get; set; }
        public byte CompletelyShipped { get; set; }
        public DateTime RequestedDeliveryDate { get; set; }
        public DateTime PromisedDeliveryDate { get; set; }
        public string ShippingTime { get; set; }
        public DateTime PlannedDeliveryDate { get; set; }
        public string ShippingAgentCode { get; set; }
        public string ShippingAgentServiceCode { get; set; }
        public int ApplFromItemEntry { get; set; }
        public string ServiceItemNo { get; set; }
        public int ApplToServiceEntry { get; set; }
        public int ServiceItemLineNo { get; set; }
        public string ServiceItemSerialNo { get; set; }
        public string ServPriceAdjmtGrCode { get; set; }
        public DateTime PostingDate { get; set; }
        public DateTime OrderDate { get; set; }
        public DateTime NeededByDate { get; set; }
        public string ShipToCode { get; set; }
        public decimal QtyToConsume { get; set; }
        public decimal QuantityConsumed { get; set; }
        public decimal QtyToConsumeBase { get; set; }
        public decimal QtyConsumedBase { get; set; }
        public string ServicePriceGroupCode { get; set; }
        public string FaultAreaCode { get; set; }
        public string SymptomCode { get; set; }
        public string FaultCode { get; set; }
        public string ResolutionCode { get; set; }
        public byte ExcludeWarranty { get; set; }
        public byte Warranty { get; set; }
        public string ContractNo { get; set; }
        public decimal ContractDisc { get; set; }
        public decimal WarrantyDisc { get; set; }
        public int ComponentLineNo { get; set; }
        public int SparePartAction { get; set; }
        public string FaultReasonCode { get; set; }
        public string ReplacedItemNo { get; set; }
        public byte ExcludeContractDiscount { get; set; }
        public int ReplacedItemType { get; set; }
        public int PriceAdjmtStatus { get; set; }
        public int LineDiscountType { get; set; }
        public int CopyComponentsFrom { get; set; }
        public string ReturnReasonCode { get; set; }
        public byte AllowLineDisc { get; set; }
        public string CustomerDiscGroup { get; set; }
        public decimal QtyPicked { get; set; }
        public decimal QtyPickedBase { get; set; }
        public byte CompletelyPicked { get; set; }
        public decimal PickQtyBase { get; set; }
    }
}
